(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function k(a){let c;null==(c=window.AFMA_Communicator)||c.addEventListener("onshow",a)};var l=class{constructor(){this.channel=4;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,c){this.g&&window.mys.pingback.setAttribute(a,c)}setData(a,c){this.g&&window.mys.pingback.setData(a,c,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}};const m=["googqscp","osdlfm"];
function p(a,c){var d;if((a.g.includes(c)||a.h.includes(c))&&(null==(d=window.performance)?0:d.getEntries)&&window.PerformanceNavigationTiming&&window.PerformanceResourceTiming){d=a.g.includes(c)?["script"]:[];var f=window.performance.getEntries(),b=0,e=0,g=0,n=0;for(const h of f)if(!h.name.includes("pagead2.googlesyndication.com/pagead/gen_204?id=mys"))if(h instanceof window.PerformanceNavigationTiming)b+=h.transferSize||0;else if(h instanceof window.PerformanceResourceTiming){f=h.initiatorType;
const t=h.transferSize||0;if(0===d.length||d.includes(f))g++,e+=0===t?1:0,n+=t}a.g.includes(c)?(a.pingback.setData(16,b),a.pingback.setData(17,n),a.pingback.setData(18,g),a.pingback.setData(19,e)):a.h.includes(c)&&(a.pingback.setData(20,n),a.pingback.setData(21,g),a.pingback.setData(22,e))}a.pingback.setData(c,window.performance.now());26===c&&q(a);a.pingback.send()}function r(a,c){a.i[c]=window.performance.now()}
function u(a,c){a.i.hasOwnProperty(c)&&(a.pingback.setData(c,window.performance.now()-a.i[c]),13===c&&q(a),a.pingback.send())}function q(a){a.pingback.setData(30,`${window.innerWidth}x${window.innerHeight}`);const {clientWidth:c,clientHeight:d}=a.context.body;a.pingback.setData(25,`${c}x${d}`)}
var w=class{constructor(){this.context=v;this.pingback=new l;this.i={};this.j={overallStart:()=>void p(this,3),overallReady:()=>void p(this,4),overallQuiet:()=>void p(this,5),overallError:()=>void p(this,6),assembleStart:()=>void r(this,7),assembleReady:()=>void u(this,7),decorateStart:()=>void r(this,8),decorateReady:()=>void u(this,8),fontStart:()=>void r(this,9),fontReady:()=>void u(this,9),spanStart:()=>void r(this,10),spanReady:()=>void u(this,10),prepareStart:()=>void r(this,11),prepareReady:()=>
void u(this,11),bindingStart:()=>void r(this,12),bindingReady:()=>void u(this,12),browserStart:()=>void r(this,13),browserStartEnd:()=>void u(this,13),browserReady:()=>void r(this,14),browserReadyEnd:()=>void u(this,14),browserQuiet:()=>void r(this,15),browserQuietEnd:()=>void u(this,15)};this.g=[23];this.h=[24]}};/*

 SPDX-License-Identifier: Apache-2.0
*/
function x(a,c){a=a.getElementsByTagName("META");for(let d=0;d<a.length;++d)if(a[d].getAttribute("name")===c)return a[d].getAttribute("content")||"";return""};function y(a){if(!a.g.hasOwnProperty("META_LOCKED")){var c=x(a.body,"custom_flags");c&&(a.g=JSON.parse(c))}}
var A=class{constructor(){var a=z;this.body=a;this.h=[];this.g={};x(a,"sampling_mod");var c=x(a,"namespace");if(!c){c="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var d=a.getElementsByTagName("META");for(let f=0;f<d.length;++f)if("namespace"===d[f].getAttribute("name")&&d[f].getAttribute("index")===(0).toString()){d[f].setAttribute("content",c);break a}d=a.querySelector("#mys-meta");d||(d=document.createElement("div"),d.id="mys-meta",d.style.position="absolute",d.style.display="none",a.appendChild(d));
a=document.createElement("META");a.setAttribute("name","namespace");a.setAttribute("content",c);a.setAttribute("index",(0).toString());d.appendChild(a)}}if(!(0<this.h.length)){a=x(this.body,"environment");for(const f of a.split("|"))f&&this.h.push(f)}y(this)}addEventListener(a,c){this.body.addEventListener(a,c)}};const z=document.getElementById("mys-content"),v=new A;
(function(){var a=new w,c;if(null!=(c=window.mys)&&c.pingback){c=a.context.body;window.addEventListener("error",b=>{var e=b.message||"";let g=!1;for(let n=0;n<m.length;++n){const h=m[n];if(e.includes(h)){e=h;g=!0;break}}e=b.type+": "+e;!g&&b.lineno&&b.colno&&(e+=` at ${b.lineno}:${b.colno}`);a.pingback.setData(1,e);a.pingback.send()});c.addEventListener("customError",b=>{let e="custom_error: ";b.detail&&(e+=b.detail.message);a.pingback.setData(2,e);a.pingback.send()});window.addEventListener("click",
b=>{const e=Date.now()-window.mys.pingback.getBaseTime();a.pingback.setData(47,`${b.clientX}x${b.clientY}@${e}`);a.pingback.send()},!0);var d;if(null!=(d=window.performance)&&d.now){window.addEventListener("DOMContentLoaded",()=>void p(a,23));window.addEventListener("load",()=>{p(a,24);setTimeout(()=>{var b;null!=(b=window.performance)&&b.getEntriesByType&&(b=performance.getEntriesByType("navigation")[0])&&(a.pingback.setData(50,b.fetchStart),a.pingback.setData(51,b.domainLookupStart),a.pingback.setData(52,
b.domainLookupEnd),a.pingback.setData(53,b.connectStart),a.pingback.setData(54,b.connectEnd),a.pingback.setData(55,b.secureConnectionStart),a.pingback.setData(56,b.requestStart),a.pingback.setData(57,b.responseStart),a.pingback.setData(58,b.responseEnd),a.pingback.setData(59,b.domInteractive),a.pingback.setData(60,b.domContentLoadedEventStart),a.pingback.setData(61,b.domContentLoadedEventEnd),a.pingback.setData(62,b.domComplete),a.pingback.setData(63,b.loadEventStart),a.pingback.setData(64,b.loadEventEnd),
a.pingback.send())},0)});k(()=>void p(a,26));var f=new Map([["DOM_CONTENT_LOADED",23],["PAGE_LOADED",24],["AFMA_ONSHOW",26],["OVERALL_READY",4],["OVERALL_QUIET",5]]);a.context.addEventListener("overallStart",()=>{var b=a.context;y(b);b=b.g.check_script_loading_at;var e=a.context;y(e);e=e.g.check_resource_loading_at;if(b){a.g=[];for(const g of b.split("|"))a.g.push(f.get(g)||23)}if(e){a.h=[];for(const g of e.split("|"))a.h.push(f.get(g)||24)}});for(const [b,e]of Object.entries(a.j))c.addEventListener(b,
e)}}})();}).call(this);
